---
name: PartyFriends
author: MlsDmitry
website: https://www.youtube.com/channel/UCoCisfxFp0ZWioLxURSnUNA
api: [3.0.0, 3.12.2, 4.0.0]
main: mlsdmitry\PartyFriends\PartyFriends
description: Invite players to play together!
version: 0.1
...